name: Publish Web App

on:
  workflow_dispatch:
    inputs:
      web_package_name:
        description: 'Name of the Android project module'
        required: true
        default: 'mifospay-web'

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read  # Read repository contents
  pages: write    # Write to GitHub Pages
  id-token: write # Write authentication tokens

jobs:
  build_web_app:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: build_and_publish_action@v1
        id: deployment
        with:
          web_package_name: ${{ inputs.web_package_name }}