name: Static Analysis & Debug Build
on:
  pull_request:
    branches:
      - dev
jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Static Analysis Check
        uses: static_analysis_check_action@v1

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android App
        uses: build_android_action@v1
        with:
          android_package_name: 'mifospay-android'

  build_desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Desktop App
        uses: build_and_publish_action@v1
        with:
          desktop_package_name: ${{ inputs.desktop_package_name }}