name: Publish Android App on Firebase
on:
  workflow_dispatch:


jobs:
  publish_android_app_on_firebase:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Android App on Firebase
        uses: publish-android-on-firebase-action@v1
        with:
          android_package_name: 'mifospay-android'

          keystore_file: ${{ secrets.KEYSTORE_FILE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD }}

          google_services: ${{ secrets.GOOGLE_SERVICES }}
          firebase_creds: ${{ secrets.FIREBASE_CREDS }}

          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'dev'




